---

- hosts: all
  become: true
  tasks:
  
  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'

  - name: install apache2 packages
    apt:
      name: apache2  
      state: latest 
    when: ansible_distribution == 'Ubuntu'
  
  - name: install php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == 'Ubuntu'

  - name: update repository index for Centos
    yum:
      update_cache: yes
    when: ansible_distribution == 'CentOS'

  - name: install apache2 packages for apache
    yum:
      name: httpd  
      state: latest 
    when: ansible_distribution == 'CentOS'
  
  - name: install php support for Centos apache
    yum:
      name: php
      state: latest
    when: ansible_distribution == 'CentOS'