---

- hosts: all
  become: true
  pre_tasks:
  
  - name: Install updates CentOS
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == 'CentOS' 
  
  - name: Install updates Ubuntu
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'


- hosts: webservers
  become: true
  tasks:     

  - name: Install apache and php for Ubuntu servers
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == 'Ubuntu'

  - name: Install apache and php packages for CentOS
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == 'CentOS' 

- hosts: databases
  become: true
  tasks:

  - name: Install mariadb package  (CentOS)
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == 'CentOS'
      
  - name: Install mariadb package  (Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == 'Ubuntu'

